# Generated by Django 5.2.6 on 2025-09-16 18:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("description", models.TextField()),
                ("thumbnail", models.URLField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("racket", "Racket"),
                            ("shoes", "Shoes"),
                            ("accesories", "Accesories"),
                            ("bags", "Bags"),
                            ("balls", "Balls"),
                        ],
                        default="update",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rating", models.FloatField(default=0.0)),
                ("weight", models.IntegerField(default=0)),
                ("brand", models.CharField(max_length=100)),
                ("product_views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
