# Generated by Django 5.2.6 on 2025-09-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("description", models.TextField()),
                ("thumbnail", models.URLField()),
                ("category", models.CharField(max_length=100)),
                ("is_featured", models.BooleanField(default=False)),
                ("stock", models.IntegerField(default=0)),
                ("rating", models.FloatField(default=0.0)),
                ("size", models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
