# Generated by Django 5.2.6 on 2025-09-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("racket", "Racket"),
                    ("balls", "Balls"),
                    ("shirt", "Shirt"),
                    ("pants", "Pants"),
                    ("rumor", "Rumor"),
                    ("analysis", "Analysis"),
                ],
                default="update",
                max_length=20,
            ),
        ),
    ]
