# Generated by Django 5.2.6 on 2025-09-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("racket", "Racket"),
                    ("shoes", "Shoes"),
                    ("accesories", "Accesories"),
                    ("bags", "Bags"),
                    ("balls", "Balls"),
                ],
                default="update",
                max_length=20,
            ),
        ),
    ]
